### ISSUE TITLE
Kustomizing the cert-manager folder in a way so that both lets encrypt and ZeroSSL is readed 

### ISSUE THREAD

**Issue by ayushghimiresharma95** [ictaiproject/Mlops#8]

**Comment by ayushghimiresharma95** [comment]
here we will creating the scripts file that first will create a .env files and then we will using that file for creating the config map file

**Comment by ayushghimiresharma95** [comment]
i have also configured the uninstall file where we will be unistalling the whole project plus it will remove the file from that folder

**Comment by ayushghimiresharma95** [comment]
# MLflow Deployment Using Kustomize with .env Configuration

This document provides a comprehensive overview of how to deploy MLflow on Kubernetes using **Kustomize** with dynamic values from a `.env` file, including:

- Resource definitions
- ConfigMap and Secret generation
- Ingress domain injection using `.env`
- Folder structure and usage guidelines

---

## 🗂 Folder Structure

Your project directory should look like this:

```
mlflow-deployment/
├── kustomization.yaml
├── config.env
├── mlflow-namespace.yaml
├── mlflow-deployment.yaml
├── mlflow-service.yaml
├── mlflow-sa.yaml
├── mlflow-virtualservice.yaml
├── mlflow-ingress.yaml
```

---

## ⚙️ kustomization.yaml

This file is the heart of the setup:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mlflow-namespace.yaml
  - mlflow-deployment.yaml
  - mlflow-service.yaml
  - mlflow-sa.yaml
  - mlflow-virtualservice.yaml
  - mlflow-ingress.yaml

configMapGenerator:
  - name: mlflow-configmap
    envs:
      - config.env
    behavior: replace

secretGenerator:
  - name: mlflow-secret
    literals:
      - DB_PASSWORD=KFSg-AYoiPdfRun64z2-w89Kk7z5cJL2IbVvSd3l8Og

replacements:
  - source:
      kind: ConfigMap
      name: mlflow-configmap
      fieldPath: data.domain
    targets:
      - select:
          kind: Ingress
          name: mlflow-ingress
        fieldPaths:
          - spec.rules.0.host
```

### Breakdown

- **resources**: YAML files needed for deployment
- **configMapGenerator**: Generates a config map using the `config.env` file
- **secretGenerator**: Creates a secret containing database password
- **replacements**: Dynamically replaces the host in the Ingress rule with the value from the config map (`domain`)

---

## 📄 config.env

This file stores dynamic values like domain, email, etc.

```env
domain=mlflow.example.com
email=admin@example.com
```

> **Note**: The path must be relative to the `kustomization.yaml` file, or you can give an absolute path.

---

## 📄 mlflow-ingress.yaml (Sample)

Make sure the target field in your Ingress matches the `replacements` path:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlflow-ingress
spec:
  rules:
    - host: PLACEHOLDER
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mlflow-service
                port:
                  number: 5000
```

The `host` will be dynamically replaced with the value from the `.env` file through the generated ConfigMap.

---

## ✅ How It Works

1. `.env` values are loaded into a ConfigMap.
2. Kustomize's `replacements` injects the domain into Ingress.
3. Secrets are securely passed for sensitive data like passwords.
4. All manifests are clean, dynamic, and reusable across environments.

---

## 🧪 Usage

To build the manifests:

```bash
kustomize build .
```

To apply:

```bash
kubectl apply -k .
```

---

## 🧼 Troubleshooting Tips

- Ensure `.env` file is **in the same folder** as `kustomization.yaml` (or provide full path).
- Use `behavior: replace` in `configMapGenerator` to avoid duplicate ConfigMap errors.
- Make sure the `name` in `secretGenerator` and `configMapGenerator` matches the ones used in `replacements` or manifests.

---

## 📝 Summary

This approach allows:
- Clean separation of configuration
- Dynamic environment-based deployments
- Easy secret management
- Declarative Kubernetes setup

---

**Comment by ayushghimiresharma95** [comment]
# Kubeflow Kustomization Setup: Mistakes and Corrections

This document highlights the issues encountered and provides a clear, corrected structure for deploying Kubeflow components using Kustomize.

---

## ❌ Mistakes Encountered

### 1. Incorrect Resource Reference Paths
You referenced directories that are not valid Kustomize bases (e.g., `must resolve to a file` errors).  
**Problem:** Trying to recursively accumulate directories without a proper `kustomization.yaml`.  
**Fix:** Ensure every directory you reference has a `kustomization.yaml`.

### 2. ConfigMap Not Found
```bash
ConfigMap "mlpipepline-ui-configmap-domain" not found; cannot merge or replace
```
**Problem:** ConfigMap not being created due to incorrect naming and missing `config.env`.
**Fix:** Use `configMapGenerator` in `kustomization.yaml` with a valid `config.env` file.

### 3. Typo in ConfigMap Name
Used `mlpipepline` (note the typo) instead of `mlpipeline` in multiple places.

### 4. Incorrect Use of Service in Replacement Target
Attempted to apply a replacement to a `Service` for TLS, which should instead be on an `Ingress` or `VirtualService`.

---

## ✅ Correct Setup Flow

### 1. File Structure

```
deployment/
└── kubeflow/
    ├── manifests/
    │   └── apps/
    │       └── pipeline/
    │           └── overlays/
    │               └── custom/
    │                   ├── kustomization.yaml
    │                   ├── config.env
    │                   ├── ml-pipeline-ui-ingress.yaml
    │                   └── ml-pipeline-ui-virtual-service.yaml
```

### 2. `config.env` Content
```env
domain=ml-pipeline.example.com
```

### 3. `kustomization.yaml` Highlights

```yaml
configMapGenerator:
  - name: mlpipeline-ui-configmap-domain
    envs:
      - config.env
    behavior: replace

replacements:
  - source:
      kind: ConfigMap
      name: mlpipeline-ui-configmap-domain
      fieldPath: data.domain
    targets:
      - select:
          kind: Ingress
          name: ml-pipeline-ui-ingress
        fieldPaths:
          - spec.rules.0.host
      - select:
          kind: VirtualService
          name: ml-pipeline-ui-virtual-service
        fieldPaths:
          - spec.hosts.0
```

### 4. Ingress Placeholder
Use a dummy value in your `ml-pipeline-ui-ingress.yaml`:
```yaml
spec:
  rules:
    - host: placeholder.domain.com  # Will be replaced dynamically
```

---

## ✅ Final Tips

- Double check all directory paths and make sure each has a `kustomization.yaml` if used as a base.
- Keep your naming consistent (especially with `ConfigMap` and `env` files).
- Validate YAML files using tools like `kubectl apply --dry-run=client`.
